{
 "title": "Flink Job / Task Manager",
 "description": "Dashboard for Job Manager and Task Manager, prepared for versions: 1.12.X, 1.13.X",
 "tags": [
  "flink",
  "task manager",
  "job manager",
  "apache"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   {
    "name": "jobmanager",
    "label": "Job Manager",
    "query": {
     "query": "label_values(flink_jobmanager_numRegisteredTaskManagers,instance)"
    }
   },
   {
    "name": "taskmanager",
    "label": "Task Manager",
    "query": {
     "query": "label_values(up{instance=~\"chainbase_taskmanager.*\"},instance)"
    }
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{instance=\"$taskmanager\"},job_name)"
    }
   },
   {
    "name": "task_name",
    "label": "Task Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{instance=\"$taskmanager\"},task_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Task Execution Time Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "chainbase_avs_task_execution_time_minutes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Checkpoints number",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(app, job_name, job_id, job) (idelta(flink_jobmanager_job_numberOfFailedCheckpoints{instance=\"$jobmanager\"}[5m])) > 0",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Received Task Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "chainbase_avs_num_task_received",
     "legendFormat": "__auto"
    },
    { "expr": "chainbase_avs_num_task_succeed", "legendFormat": "__auto" },
    { "expr": "chainbase_avs_num_task_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{instance=~\"$jobmanager\"}",
     "legendFormat": "taskSlotsTotal"
    },
    {
     "expr": "flink_jobmanager_taskSlotsAvailable{instance=~\"$jobmanager\"}",
     "legendFormat": "taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "Task Managers Numbers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{instance=~\"$jobmanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RunningJobs",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs{instance=~\"$jobmanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Restarts Rait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(app, job_name, job_id, job) (idelta(flink_jobmanager_job_fullRestarts{instance=\"$jobmanager\"}[5m])) > 1",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Job Manager (JVM - CPU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_CPU_Load{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_Status_JVM_CPU_Time{instance=~\"$jobmanager\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Threads_Count{instance=~\"$jobmanager\"}",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (JVM - Memory Usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Direct",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mapped",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Mapped_MemoryUsed{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Metaspace_Used{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (JVM - Garbage Collector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Young GC Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(flink_jobmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time{instance=~\"$jobmanager\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Old GC Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(flink_jobmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time{instance=~\"$jobmanager\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (Slots & Jobs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Task Managers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRegisteredTaskManagers{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Task Slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsTotal{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available Task Slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsAvailable{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Runnings Jobs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRunningJobs{instance=~\"$jobmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Job Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_numRestarts{job_name=~\"$job_name\", instance=~\"$jobmanager\"}",
       "legendFormat": "{{job_name}} on {{instance}}"
      }
     ]
    },
    {
     "title": "Job Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_fullRestarts{job_name=~\"$job_name\", instance=~\"$jobmanager\"}",
       "legendFormat": "{{job_name}} on {{instance}}"
      }
     ]
    },
    {
     "title": "Job Restartine Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_restartingTime{job_name=~\"$job_name\", instance=~\"$jobmanager\"}",
       "legendFormat": "{{job_name}} ({{job_id}}) on {{instance}}"
      }
     ]
    },
    {
     "title": "Job Uptime",
     "type": "stat",
     "gridPos": { "h": 10, "w": 21, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_uptime{job_name=~\"$job_name\", instance=~\"$jobmanager\"}",
       "legendFormat": "{{job_name}}({{instance}})"
      }
     ]
    },
    {
     "title": "Uptime Derscription",
     "type": "text",
     "gridPos": { "h": 10, "w": 3, "x": 21, "y": 78 },
     "options": {
      "content": "# Uptime Description\n\n| Color | Status|\n|---|---|\n| Green | < 1 Hour |\n| Yellow | >= 1 Hour  |\n| Orange | >= 6 Hours |\n| Purple | >= 1 Day |\n| Red | >= 3 days |\n"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Job Manager (Checkpoints)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Completed Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_job_numberOfCompletedCheckpoints{job_name=~\"$job_name\", instance=~\"$jobmanager\"}[1m])",
       "legendFormat": "{{job_name}} on {{instance}}"
      }
     ]
    },
    {
     "title": "In Progress Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 63 },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_job_numberOfInProgressCheckpoints{job_name=~\"$job_name\", instance=~\"$jobmanager\"}[1m])",
       "legendFormat": "{{job_name}} on {{instance}}"
      }
     ]
    },
    {
     "title": "Failed Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 63 },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_job_numberOfFailedCheckpoints{job_name=~\"$job_name\", instance=~\"$jobmanager\"}[1m])",
       "legendFormat": "{{job_name}} on {{instance}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{job_name=~\"$job_name\", instance=~\"$jobmanager\"}",
       "legendFormat": "{{job_name}} on {{instance}}"
      }
     ]
    },
    {
     "title": "Last Checkpoint Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{job_name=~\"$job_name\", instance=~\"$jobmanager\"}",
       "legendFormat": "{{job_name}} on {{instance}}"
      }
     ]
    },
    {
     "title": "Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 74 },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_job_totalNumberOfCheckpoints{job_name=~\"$job_name\", instance=~\"$jobmanager\"}[1m])",
       "legendFormat": "{{job_name}} on {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (JVM - CPU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Load{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_Status_JVM_CPU_Time{instance=~\"$taskmanager\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Threads_Count{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (JVM - Memory Usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Non Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Direct",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mapped",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_MemoryUsed{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Metaspace_Used{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (JVM - Garbage Collector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Young Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time{instance=~\"$taskmanager\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Old Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time{instance=~\"$taskmanager\"}[2m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Memory - Flink)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Managed",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Flink_Memory_Managed_Used{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Memory - Shuffle Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemory{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemorySegments{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_UsedMemory{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemory{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Used Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_UsedMemorySegments{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemorySegments{instance=~\"$taskmanager\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Diag)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Is Back Pressured",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_isBackPressured{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Idle Time Ms (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_idleTimeMsPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Checkpoint Alignment Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_checkpointStartDelayNanos{instance=~\"$taskmanager\",job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Checkpoint Alignment Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 69 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_checkpointAlignmentTime{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager  (Job Task - General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number Buffers in Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBuffersInLocal{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers in Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBuffersInLocalPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers in Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_numBuffersInRemote{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers in Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBuffersInRemotePerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBuffersOut{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Buffers Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBuffersOutPerSecond{instance=~\"$taskmanager\",job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBytesIn{instance=~\"$taskmanager\",job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 4, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBytesInPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 8, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBytesInLocal{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBytesInLocalPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBytesInRemote{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBytesInRemotePerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numBytesOut{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numBytesOutPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Records In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numRecordsIn{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes In (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numRecordsInPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Records Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_numRecordsOut{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Bytes Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_numRecordsOutPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Buffers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "In Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inPoolUsage{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 71 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputQueueLength{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Exclusive Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 71 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputExclusiveBuffersUsage{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Out Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_outPoolUsage{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Output Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 81 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_outputQueueLength{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Floating Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 81 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_buffers_inputFloatingBuffersUsage{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Operator)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number Late Records Dropped",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numLateRecordsDropped",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Records In",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 4, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_operator_numRecordsIn{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Records Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 9, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_operator_numRecordsInPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Number Records In",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 14, "y": 72 },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_operator_numRecordsOut{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Num Records Out (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 72 },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Job Task - Shuffle Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Input Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputQueueLength{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Output Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outputQueueLength{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "In Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inPoolUsage{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Out Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Output_Buffers_outPoolUsage{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Floating Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputFloatingBuffersUsage{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Exclusive Buffers Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_Buffers_inputExclusiveBuffersUsage{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Buffers In Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocal{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Buffers In Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInLocalPerSecond{instance=~\"$taskmanager\",job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Buffers In Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemote{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Num Buffers In Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBuffersInRemotePerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Num Bytes In Local",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInLocal{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Bytes In Local (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInLocalPerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Bytes In Remote",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInRemote{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    },
    {
     "title": "Input Number Bytes In Remote (per Second)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(flink_taskmanager_job_task_Shuffle_Netty_Input_numBytesInRemotePerSecond{instance=~\"$taskmanager\", job_name=~\"$job_name\", task_name=~\"$task_name\"}[1m])",
       "legendFormat": "{{job_name}} ({{job_id}} / {{task_id}}) {{tm_id}}"
      }
     ]
    }
   ]
  }
 ]
}